var gvjs_MP="#990000",gvjs_NP="annotationText",gvjs_OP="certainty";function gvjs_PP(a,b){var c=new gvjs_K,d=b.ea(),e=b.aa(),f=a.Z(0)!=gvjs_f;f&&c.ke(a.Z(0),a.Ka(0));for(var g=f?1:0,h=g;h<e;++h)c.ke({type:a.Z(h),label:a.Ka(h),role:gvjs__w}),c.ke({type:b.Z(h),label:b.Ka(h),role:gvjs_bv});c.Bp(d);for(var k=0;k<d;++k){f&&(h=b.getValue(k,0),c.jc(k,0,h));var l=g;for(h=g;h<e;++h){var m=a.getValue(k,h);c.jc(k,l,m);l+=1;m=b.getValue(k,h);c.jc(k,l,m);l+=1}}return c}
gvjs_$K.prototype.dfa=gvjs_U(153,function(a,b){if(!this.zk.pu)return!1;var c=this.K.range;if(null==c.Xh||null==c.Wh)return!1;a=gvjs_dL(this,a,b);a=gvjs_kL(this,a.Xh,a.Wh,gvjs_wu);this.K.dh=null;return a});gvjs_NK.prototype.co=gvjs_U(152,function(a,b){if(this.Vg===gvjs_bx)return gvjs_PP(a,b);throw Error("Cannot compute diff for this chart type.");});gvjs_OK.prototype.co=gvjs_U(151,function(a,b){return gvjs_PP(a,b)});gvjs_YK.prototype.co=gvjs_U(150,function(a,b){return gvjs_PP(a,b)});
function gvjs_QP(a){var b=new gvjs_hF;b.ra=function(){return a};return b}function gvjs_RP(a){gvjs_NK.call(this,a);this.Ud(gvjs_c,gvjs_1x,gvjs_R)}gvjs_n(gvjs_RP,gvjs_NK);function gvjs_SP(a){gvjs_NK.call(this,a);this.Ud(gvjs_c,gvjs_e,gvjs_R,"sparkline")}gvjs_n(gvjs_SP,gvjs_NK);function gvjs_TP(a){gvjs_NK.call(this,a);this.Ud(gvjs_Au)}gvjs_n(gvjs_TP,gvjs_NK);function gvjs_UP(a){gvjs_NK.call(this,a);this.Ud(gvjs_c,gvjs_ou,gvjs_T)}gvjs_n(gvjs_UP,gvjs_NK);
gvjs_UP.prototype.co=function(a,b){return gvjs_PP(a,b)};function gvjs_VP(a){gvjs_NK.call(this,a);this.Ud(gvjs_c,gvjs_Hu,gvjs_R)}gvjs_n(gvjs_VP,gvjs_NK);function gvjs_WP(a){gvjs_NK.call(this,a);this.Ud(gvjs_c,gvjs_ou,gvjs_R)}gvjs_n(gvjs_WP,gvjs_NK);gvjs_WP.prototype.co=function(a,b){return gvjs_PP(a,b)};function gvjs_XP(a){gvjs_NK.call(this,a);this.Ud(gvjs_5v,gvjs_ou,gvjs_R)}gvjs_n(gvjs_XP,gvjs_NK);gvjs_p(gvjs_nc,gvjs_NK,void 0);gvjs_NK.prototype.draw=gvjs_NK.prototype.draw;
gvjs_NK.prototype.clearChart=gvjs_NK.prototype.Ib;gvjs_NK.prototype.getImageURI=gvjs_NK.prototype.Kh;gvjs_NK.prototype.getSelection=gvjs_NK.prototype.getSelection;gvjs_NK.prototype.setSelection=gvjs_NK.prototype.setSelection;gvjs_NK.prototype.dump=gvjs_NK.prototype.dump;gvjs_NK.prototype.getChartLayoutInterface=gvjs_NK.prototype.vo;gvjs_NK.prototype.getContainer=gvjs_NK.prototype.getContainer;gvjs_NK.prototype.setAction=gvjs_NK.prototype.kj;gvjs_NK.prototype.getAction=gvjs_NK.prototype.Yg;
gvjs_NK.prototype.removeAction=gvjs_NK.prototype.gj;gvjs_p(gvjs_bc,gvjs_WK,void 0);gvjs_WK.prototype.draw=gvjs_WK.prototype.draw;gvjs_WK.prototype.clearChart=gvjs_WK.prototype.Ib;gvjs_WK.prototype.getImageURI=gvjs_WK.prototype.Kh;gvjs_WK.prototype.getSelection=gvjs_WK.prototype.getSelection;gvjs_WK.prototype.setSelection=gvjs_WK.prototype.setSelection;gvjs_WK.prototype.setAction=gvjs_WK.prototype.kj;gvjs_WK.prototype.getAction=gvjs_WK.prototype.Yg;gvjs_WK.prototype.removeAction=gvjs_WK.prototype.gj;
gvjs_p(gvjs_cc,gvjs_UP,void 0);gvjs_UP.prototype.computeDiff=gvjs_UP.prototype.co;gvjs_UP.prototype.draw=gvjs_UP.prototype.draw;gvjs_UP.prototype.clearChart=gvjs_UP.prototype.Ib;gvjs_UP.prototype.getImageURI=gvjs_UP.prototype.Kh;gvjs_UP.prototype.getSelection=gvjs_UP.prototype.getSelection;gvjs_UP.prototype.setSelection=gvjs_UP.prototype.setSelection;gvjs_UP.prototype.setAction=gvjs_UP.prototype.kj;gvjs_UP.prototype.getAction=gvjs_UP.prototype.Yg;gvjs_UP.prototype.removeAction=gvjs_UP.prototype.gj;
gvjs_p(gvjs_dc,gvjs_TP,void 0);gvjs_TP.prototype.draw=gvjs_TP.prototype.draw;gvjs_TP.prototype.clearChart=gvjs_TP.prototype.Ib;gvjs_TP.prototype.getImageURI=gvjs_TP.prototype.Kh;gvjs_TP.prototype.getSelection=gvjs_TP.prototype.getSelection;gvjs_TP.prototype.setSelection=gvjs_TP.prototype.setSelection;gvjs_TP.prototype.setAction=gvjs_TP.prototype.kj;gvjs_TP.prototype.getAction=gvjs_TP.prototype.Yg;gvjs_TP.prototype.removeAction=gvjs_TP.prototype.gj;gvjs_p(gvjs_fc,gvjs_VP,void 0);
gvjs_VP.prototype.draw=gvjs_VP.prototype.draw;gvjs_VP.prototype.clearChart=gvjs_VP.prototype.Ib;gvjs_VP.prototype.getImageURI=gvjs_VP.prototype.Kh;gvjs_VP.prototype.getSelection=gvjs_VP.prototype.getSelection;gvjs_VP.prototype.setSelection=gvjs_VP.prototype.setSelection;gvjs_VP.prototype.setAction=gvjs_VP.prototype.kj;gvjs_VP.prototype.getAction=gvjs_VP.prototype.Yg;gvjs_VP.prototype.removeAction=gvjs_VP.prototype.gj;gvjs_p(gvjs_zc,gvjs_XP,void 0);gvjs_XP.prototype.draw=gvjs_XP.prototype.draw;
gvjs_XP.prototype.clearChart=gvjs_XP.prototype.Ib;gvjs_XP.prototype.getImageURI=gvjs_XP.prototype.Kh;gvjs_XP.prototype.getSelection=gvjs_XP.prototype.getSelection;gvjs_XP.prototype.setSelection=gvjs_XP.prototype.setSelection;gvjs_XP.prototype.setAction=gvjs_XP.prototype.kj;gvjs_XP.prototype.getAction=gvjs_XP.prototype.Yg;gvjs_XP.prototype.removeAction=gvjs_XP.prototype.gj;gvjs_p(gvjs_kc,gvjs_WP,void 0);gvjs_WP.prototype.computeDiff=gvjs_WP.prototype.co;gvjs_WP.prototype.draw=gvjs_WP.prototype.draw;
gvjs_WP.prototype.clearChart=gvjs_WP.prototype.Ib;gvjs_WP.prototype.getImageURI=gvjs_WP.prototype.Kh;gvjs_WP.prototype.getSelection=gvjs_WP.prototype.getSelection;gvjs_WP.prototype.setSelection=gvjs_WP.prototype.setSelection;gvjs_WP.prototype.setAction=gvjs_WP.prototype.kj;gvjs_WP.prototype.getAction=gvjs_WP.prototype.Yg;gvjs_WP.prototype.removeAction=gvjs_WP.prototype.gj;gvjs_p(gvjs_mc,gvjs_ZK,void 0);gvjs_ZK.prototype.draw=gvjs_ZK.prototype.draw;gvjs_ZK.prototype.clearChart=gvjs_ZK.prototype.Ib;
gvjs_ZK.prototype.getImageURI=gvjs_ZK.prototype.Kh;gvjs_ZK.prototype.getSelection=gvjs_ZK.prototype.getSelection;gvjs_ZK.prototype.setSelection=gvjs_ZK.prototype.setSelection;gvjs_ZK.prototype.setAction=gvjs_ZK.prototype.kj;gvjs_ZK.prototype.getAction=gvjs_ZK.prototype.Yg;gvjs_ZK.prototype.removeAction=gvjs_ZK.prototype.gj;gvjs_p(gvjs_Hc,gvjs_XK,void 0);gvjs_XK.prototype.draw=gvjs_XK.prototype.draw;gvjs_XK.prototype.clearChart=gvjs_XK.prototype.Ib;gvjs_XK.prototype.getImageURI=gvjs_XK.prototype.Kh;
gvjs_XK.prototype.getSelection=gvjs_XK.prototype.getSelection;gvjs_XK.prototype.setSelection=gvjs_XK.prototype.setSelection;gvjs_XK.prototype.setAction=gvjs_XK.prototype.kj;gvjs_XK.prototype.getAction=gvjs_XK.prototype.Yg;gvjs_XK.prototype.removeAction=gvjs_XK.prototype.gj;gvjs_p(gvjs_Rc,gvjs_OK,void 0);gvjs_OK.prototype.computeDiff=gvjs_OK.prototype.co;gvjs_OK.prototype.draw=gvjs_OK.prototype.draw;gvjs_OK.prototype.clearChart=gvjs_OK.prototype.Ib;gvjs_OK.prototype.getImageURI=gvjs_OK.prototype.Kh;
gvjs_OK.prototype.getSelection=gvjs_OK.prototype.getSelection;gvjs_OK.prototype.setSelection=gvjs_OK.prototype.setSelection;gvjs_OK.prototype.setAction=gvjs_OK.prototype.kj;gvjs_OK.prototype.getAction=gvjs_OK.prototype.Yg;gvjs_OK.prototype.removeAction=gvjs_OK.prototype.gj;gvjs_p(gvjs_Vc,gvjs_YK,void 0);gvjs_YK.prototype.computeDiff=gvjs_YK.prototype.co;gvjs_YK.prototype.draw=gvjs_YK.prototype.draw;gvjs_YK.prototype.clearChart=gvjs_YK.prototype.Ib;gvjs_YK.prototype.getImageURI=gvjs_YK.prototype.Kh;
gvjs_YK.prototype.getSelection=gvjs_YK.prototype.getSelection;gvjs_YK.prototype.setSelection=gvjs_YK.prototype.setSelection;gvjs_YK.prototype.setAction=gvjs_YK.prototype.kj;gvjs_YK.prototype.getAction=gvjs_YK.prototype.Yg;gvjs_YK.prototype.removeAction=gvjs_YK.prototype.gj;gvjs_p(gvjs_Xc,gvjs_SP,void 0);gvjs_SP.prototype.draw=gvjs_SP.prototype.draw;gvjs_SP.prototype.clearChart=gvjs_SP.prototype.Ib;gvjs_SP.prototype.getImageURI=gvjs_SP.prototype.Kh;gvjs_SP.prototype.getSelection=gvjs_SP.prototype.getSelection;
gvjs_SP.prototype.setSelection=gvjs_SP.prototype.setSelection;gvjs_SP.prototype.setAction=gvjs_SP.prototype.kj;gvjs_SP.prototype.getAction=gvjs_SP.prototype.Yg;gvjs_SP.prototype.removeAction=gvjs_SP.prototype.gj;gvjs_p(gvjs_Yc,gvjs_RP,void 0);gvjs_RP.prototype.draw=gvjs_RP.prototype.draw;gvjs_RP.prototype.clearChart=gvjs_RP.prototype.Ib;gvjs_RP.prototype.getImageURI=gvjs_RP.prototype.Kh;gvjs_RP.prototype.getSelection=gvjs_RP.prototype.getSelection;gvjs_RP.prototype.setSelection=gvjs_RP.prototype.setSelection;
gvjs_RP.prototype.setAction=gvjs_RP.prototype.kj;gvjs_RP.prototype.getAction=gvjs_RP.prototype.Yg;gvjs_RP.prototype.removeAction=gvjs_RP.prototype.gj;gvjs_p(gvjs_Tc,gvjs_$K,void 0);gvjs_$K.prototype.draw=gvjs_$K.prototype.draw;gvjs_$K.prototype.clearChart=gvjs_$K.prototype.Ib;gvjs_$K.prototype.getRange=gvjs_$K.prototype.bP;gvjs_$K.prototype.setRange=gvjs_$K.prototype.dfa;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
gvjs_ch(gvjs_b);function gvjs_YP(a){return(new gvjs_On).ed().sanitize(a)};
